package com.dayton.drone.database.entry;

import android.content.Context;

import com.dayton.drone.database.bean.AlarmBean;

import net.medcorp.library.ble.util.Optional;

import java.util.ArrayList;
import java.util.List;

import io.realm.Realm;


public class AlarmDatabaseHelper {

    private Realm realm;
    public AlarmDatabaseHelper(Context context) {
        realm = Realm.getDefaultInstance();
    }

    /**
     *
     * @param object : this is  an object generated by "new" function
     * @return
     */
    public Optional<AlarmBean> add( AlarmBean object) {
        realm.beginTransaction();
        AlarmBean alarmBean = realm.copyToRealm(object);
        realm.commitTransaction();
        return new Optional<>(alarmBean);
    }

    /**
     *
     * @param object: this is a query object from database
     *
     */
    public void update(AlarmBean object) {
        realm.beginTransaction();
        realm.insertOrUpdate(object);
        realm.commitTransaction();
    }

    /**
     *
     * @param object: this is a query object from database
     * @return
     */
    public void remove(AlarmBean object) {
        realm.beginTransaction();
        object.deleteFromRealm();
        realm.commitTransaction();
    }

    /**
     *
     * @return query list of AlarmBean, user can use this list to update/remove
     */
    public List<AlarmBean> get() {
        return realm.where(AlarmBean.class).findAll();
    }
}
