package com.dayton.drone.database.bean;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * Created by boy on 2016/4/12.
 * Gailly fix table struct
 */

@DatabaseTable(tableName = "tb_user")
public class UserBean {

    /**
     * field name and initialize value, Primary field
     */
    public static final String fID = "id";
    @DatabaseField(generatedId = true)
    private int id = 1;

    /**
     * default age
     */
    public static final String fAge = "age";
    @DatabaseField
    private int age = 35;

    /**
     * default weight, 75kg
     */
    public static final String fWeight = "weight";
    @DatabaseField
    private double weight = 75;

    /**
     * default height, 175cm
     */
    public static final String fHeight = "height";
    @DatabaseField
    private int height = 175;

    /**
     * Sex = 0, female, sex = 1, male
     */
    public static  final String fGender = "gender";
    @DatabaseField
    private int gender = 1;

    /**
     * first name
     */
    public  static final String fFirstName = "firstName";
    @DatabaseField
    private String firstName;

    /**
     * last name
     */
    public static final String fLastName = "lastName";
    @DatabaseField
    private String lastName;

    /**
     * average stride length in "CM",default 60cm
     */
    public static final String fStrideLength = "strideLength";
    @DatabaseField
    private int strideLength = 60;

    /**
     * this is generated by Drone API when register
     */
    public static final String fUserID = "userID";
    @DatabaseField
    private String userID;

    public static final String fUserEmail = "userEmail";
    @DatabaseField
    private String userEmail;

    public static final String fUserPassword = "userPassword";
    @DatabaseField
    private String userPassword;

    public static final String fUserIsLogin = "userIsLogin";
    @DatabaseField
    private boolean userIsLogin;


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public int getGender() {
        return gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public int getStrideLength() {
        return strideLength;
    }

    public void setStrideLength(int strideLength) {
        this.strideLength = strideLength;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserPassword() {
        return userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public boolean isUserIsLogin() {
        return userIsLogin;
    }

    public void setUserIsLogin(boolean userIsLogin) {
        this.userIsLogin = userIsLogin;
    }
}
